self = "br1-ff00_0_1-2"
local_as = "1-ff00:0:1"
host_port = 30041
topology = "gen/ASff00_0_1/topology.json"
internal_interfaces = [
    { ip = "10.2.0.1", port = 31004 },
    { ip = "10.2.0.2", port = 31004 }
]
