self = "br1-ff00_0_1-4"
local_as = "1-ff00:0:1"
host_port = 30041
topology = "gen/ASff00_0_1/topology.json"
internal_interfaces = [
    { ip = "10.2.0.5", port = 31008},
    { ip = "10.2.0.6", port = 31008}
]
